input:
	../../bin/triangle2gmsh CoarseCorner_CoordinateMesh_1_checkpoint_0
	../../bin/triangle2gmsh CoarseCorner_CoordinateMesh_1_checkpoint_1
	../../bin/triangle2gmsh CoarseCorner_CoordinateMesh_1_checkpoint_2

clean-run:
	rm -rf output* *.log *.err *.err-* *.log-*
	rm -rf flredecomp_out

clean: clean-run
