input:	clean
	cp src/MMS_A.msh .
	cp src/MMS_B.msh .
	cp src/MMS_C.msh .
	cp src/MMS_D.msh .

clean:
	rm -rf *.pvtu *.stat *.s *.log-? *.err-? *.halo *.node *.ele *.edge *checkpoint*
	rm -rf MMS_?_?
	rm -rf *flredecomp*
