input:	clean
#	../../debug/bin/gmsh2triangle --2d src/MMS_A.msh
#	../../debug/bin/gmsh2triangle --2d src/MMS_B.msh
#	../../debug/bin/gmsh2triangle --2d src/MMS_C.msh
#	../../debug/bin/gmsh2triangle --2d src/MMS_D.msh
#	../../debug/bin/periodise MMS_A.flml
#	../../debug/bin/periodise MMS_B.flml
#	../../debug/bin/periodise MMS_C.flml
#	../../debug/bin/periodise MMS_D.flml

clean:
#	rm -f *.vtu *.stat *.s *.log *.node *.ele *.edge *checkpoint*
